// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Podium.Persistence.Migrations;

#nullable disable

namespace Podium.Persistence.Migrations
{
    [DbContext(typeof(PodiumContext))]
    partial class PodiumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DebateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DebateId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Debate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Debates");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.DebateJuries", b =>
                {
                    b.Property<int>("DebateId")
                        .HasColumnType("int");

                    b.Property<int>("JuryId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("DebateId", "JuryId");

                    b.HasIndex("JuryId");

                    b.ToTable("DebateJuries");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.DebateParticipants", b =>
                {
                    b.Property<int>("DebateId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DebateId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("DebateParticipants");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DebateId")
                        .HasColumnType("int");

                    b.Property<int>("JuryId")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DebateId");

                    b.HasIndex("JuryId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Users.Jury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Juries");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Users.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Attendance", b =>
                {
                    b.HasOne("Podium.Domain.Entities.Sessions.Debate", "Debate")
                        .WithMany("Attendances")
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Podium.Domain.Entities.Users.Participant", "Participant")
                        .WithMany("Attendances")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Debate");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Debate", b =>
                {
                    b.HasOne("Podium.Domain.Entities.Sessions.Topic", "Topic")
                        .WithMany("Debates")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.DebateJuries", b =>
                {
                    b.HasOne("Podium.Domain.Entities.Sessions.Debate", "Debate")
                        .WithMany("Juries")
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Podium.Domain.Entities.Users.Jury", "Jury")
                        .WithMany("Debates")
                        .HasForeignKey("JuryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debate");

                    b.Navigation("Jury");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.DebateParticipants", b =>
                {
                    b.HasOne("Podium.Domain.Entities.Sessions.Debate", "Debate")
                        .WithMany("Participants")
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Podium.Domain.Entities.Users.Participant", "Participant")
                        .WithMany("Debates")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debate");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Evaluation", b =>
                {
                    b.HasOne("Podium.Domain.Entities.Sessions.Debate", "Debate")
                        .WithMany("Evaluations")
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Podium.Domain.Entities.Users.Jury", "Jury")
                        .WithMany("Evaluations")
                        .HasForeignKey("JuryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Podium.Domain.Entities.Users.Participant", null)
                        .WithMany("Evaluations")
                        .HasForeignKey("ParticipantId");

                    b.Navigation("Debate");

                    b.Navigation("Jury");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Debate", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Evaluations");

                    b.Navigation("Juries");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Sessions.Topic", b =>
                {
                    b.Navigation("Debates");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Users.Jury", b =>
                {
                    b.Navigation("Debates");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("Podium.Domain.Entities.Users.Participant", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Debates");

                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
